/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 709cea9423ee1821132b4953d637cab1)
interface __BaseEnv_Env {
	SHIKIMORI_CLIENT_ID: "NuL115GhQetODbWxWIKOKEt9E2IMtUqGkY9zdQacpBM";
	ANIMIX_PROXY_ORIGIN: "https://animix.app";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SHIKIMORI_CLIENT_ID" | "ANIMIX_PROXY_ORIGIN">> {}
}
